RPI_website/urls.py
from django.contrib import admin
from django.urls import path, include 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('setupExperimentApp.urls'))
]

setupExperimentApp/urls.py
""" defines URL patterns for setupExperimentApp """

from django.urls import path 
from . import views

app_name = 'setupExperimentApp'
urlpatterns = [ # var for storing list of individual pages 
    # Example: 
        # views.index specifies which function to call in views.py
        # name='index' names this url pattern so we can refer to it easily later on 
        # path('', views.index, name='index'), 
    
    # path( '', views.HomePageView.as_view() ), 
    path( '', views.experiments, name='experiments'), 


    # Page for viewing an existing experiment's details. 
    path('view_experiment/<int:exp_id>/', views.view_experiment, name='view_experiment'), 

    # Page for editing an existing experiment 
    path('edit_experiment/<int:exp_id>/', views.edit_experiment, name='edit_experiment'), 

    # Page for adding a new experiment 
    path('new_experiment/', views.new_experiment, name='new_experiment'), 


    # Page for adding a new Script to an experiment 
    path('new_script/<int:exp_id>/', views.new_script, name='new_script'), 
    

]

setupExperimentApp/models.py
from django.db import models
from pychartjs import BaseChart, ChartType, Color 

# Create your models here.

# Step 1 in writing database web app is to define models 
# models – essentially, your database layout, with additional metadata.


class Experiment(models.Model): 
    user_name = models.CharField(max_length=200)
    date = models.DateTimeField('date', auto_now_add=True)
    # by placing ForeignKey(Experiment) in Script Class, we give the Experiment class instances access to this list through the use of Script_set
    # def __str__(self): 
    #    return str(self.date)

class Script(models.Model): 
    experiment = models.ForeignKey(Experiment, on_delete=models.CASCADE)
    SCRIPT_CHOICES = [ ('Magazine', 'Magazine'), 
                       ('Autoshape', 'Autoshape') ]
    type = models.TextField(choices = SCRIPT_CHOICES)
    
    # GANTT CHART # # # # # # # # 
    class MyBarGraph(BaseChart): 
        
        type = ChartType.HorizontalBar

        class labels: ["1", "2", "3", "4"],   # FOR ALL DATA POINTS TO SHOW UP YOU MUST HAVE THE CORRECT NUMBER OF LABELS LISTED! 
        
        class data: 
            
            class dataset1: 
                data = 0, 100, 150, 600
                backgroundColor = Color.RGBA(63,103,126,0)
                hoverBackgroundColor = Color.RGBA(50,90,100,0)
            class dataset2: 
                data = 100, 100, 200, 200, 100,
                backgroundColor = [Color.Red, Color.Green, Color.Blue, Color.Yellow]
        
        class options:

            title = {"text": "TITLE", "display": True} 
            animation = {"duration": 10}
            hover = {"animationDuration": 10 }
            responsiveAnimationDuration = 0

            legend = {
                    'display': 'false', 
                    'position': 'bottom', 
                    'labels': {
                        'fontColor': Color.Gray, 
                        'fullWidth': True
                        }
                    }
            scales = {
                "xAxes": [{
                    "label": "Durations", 
                    "ticks": { 
                        "beginAtZero": True, 
                    }, 
                    "gridLines": { }, 
                    "stacked": True, 
                }], 
                "yAxes": [{
                    "id": "events",
                    "gridLines": { 
                        "display":False, 
                        "color": "#fff", 
                        "zeroLineColor": "#fff", 
                        "zeroLineWidth": 0, 
                    }, 
                    "ticks": {
                        # "callback": "<<function(value, index, values) {return value + ' Big Ones';}>>",
                    }, 
                    "stacked": True, 
                }], 
                "legend":{
                    "display":False
                }
            }
    
    
    graph = MyBarGraph() 
    graphJSON = graph.get() 
    
    
    

    # # # # # # # # # # # # # # # 

setupExperimentApp/forms.py
from django import forms 
from .models import Experiment, Script

class ExperimentForm(forms.ModelForm): 
    class Meta: 
        model = Experiment
        fields = ['user_name']
        labels = {'user_name':'user_name'}


class ScriptForm(forms.ModelForm): 
    class Meta: 
        model = Script
        fields = ['type']
        labels = {'type':'type'}
        # experiment = Experiment.objects.latest('date')
        # script = forms.ModelMultipleChoiceField(queryset=Experiment.)

setupExperimentApp/views.py
from django.shortcuts import render, redirect
from django.views.generic import TemplateView
from django.views.generic.base import View
from django.urls import reverse 
from .models import Experiment
from .forms import ExperimentForm, ScriptForm


import plotly
from pychartjs import BaseChart, ChartType, Color 
import plotly.express as px 
import pandas as pd 

# Create your views here.
'''class HomePageView(TemplateView): 
    def get(self, request, **kwargs): # expects an HTTP GET request to the url defined in the urls.py file 
        return render(request, 'index.html', context=None) # renders a template called index.html
'''
def experiments(request): 
    experiments = Experiment.objects.all()
    context = {'experiments': experiments}
    return render(request, 'index.html', context)

def view_experiment(request, exp_id): 
    ''' View an Experiment. Option to edit on this page. '''
    id = exp_id 
    exp = Experiment.objects.get(id = exp_id)
    user_name = exp.user_name
    script_set = exp.script_set.all()
    date = exp.date 
    
    context = {'experiment':exp, 'id':id, 'user_name':user_name, 'date':date, 'script_set':script_set}

    return render(request, 'view_experiment.html', context)

def edit_experiment(request, exp_id): 
    '''Edit an Existing Experiment's Scripts'''
    id = exp_id 
    exp = Experiment.objects.get(id = exp_id)
    user_name = exp.user_name
    script_set = exp.script_set.all
    print(user_name)
    date = exp.date 

    if request.method != 'POST': 
        # inital request to edit, fill form with current entry  
        form = ExperimentForm(instance=exp) 
        print("BLANK")
    else: 
        # POST data submitted; process data 
        form = ExperimentForm(instance=exp, data=request.POST) 
        if form.is_valid(): 
            form.save()
            return redirect('setupExperimentApp:view_experiment',id) # HELPFUL LINE TO REMEMBER for navigating between pages 
            # return redirect('.', exp_id=exp.id)
    # Display a blank or invalid form 
    context = {'experiment':exp, 'id':id, 'user_name':user_name, 'date':date, 'script_set':script_set, 'form':form}
    return render(request, 'edit_experiment.html', context)


def new_experiment(request): 
    ''' Add a new experiment to the experiment index '''
    if request.method != 'POST': 
        # no data submitted create a blank form 
        form = ExperimentForm() 
    else: 
        # POST data submitted; process data 
        form = ExperimentForm(data=request.POST)
        if form.is_valid(): 
            form.save() 
            return redirect('/')
    
    # display a blank or invalid form 
    context = {'form':form}
    return render(request, 'new_experiment.html', context)


def new_script(request, exp_id): 
    ''' Add a new script to an experiment (specified by exp_id) '''

    experiment = Experiment.objects.get(id=exp_id)

    if request.method != 'POST': 
        # no data submitted, create a blank form 
        form = ScriptForm() 
    else: 
        # POST data submitted; process data 
        form = ScriptForm(data=request.POST) 
        if form.is_valid(): 
            new_entry = form.save(commit=False)
            new_entry.experiment = experiment 
            new_entry.save() 
            form.save() 
            return redirect('setupExperimentApp:view_experiment',exp_id)
    
    # display a blank or invalid form 
    context = {'experiment':experiment, 'form':form}
    return render(request, 'new_script.html', context)

setupExperimentApp/templates/edit_experiment.html
<!DOCTYPE html> 

<html>
    <head> 
        <meta charset="utf-8"> 
    </head>

    <body>
        <h1> Edit An Experiment's Details </h1>
        <!--  ExperimentForm() used for editing a specific experiment's model fields  -->

        <p>
            {{ id }} / {{ user_name }} / {{ date }} 
        </p>
            {{ script_set }} 


        <form action='.' method='post'>
            {%csrf_token %} 
            {{ form.as_p }}
            <button name = "submit">Save Changes</button>
        </form>
    
    </body>

setupExperimentApp/templates/index.html
<!-- Home Page -->
<!DOCTYPE html> 

<html>
    <head> 
        <meta charset="utf-8"> 
        <title>Experiment Setup</title>
        <style>
            table, th, td { border: 1px solid black;}
        </style>
    </head>


    <body>
        <h1> Experiment Index </h1>
        <table>
            <tr> 
                <th> Experiment id </th>
                <th> User </th>
                <th> Date </th>
                <th> Scripts </th> 
                <th> Link to Experiment Details </th> 
            </tr>
            {% for exp in experiments %}
            <tr> 
                <td> {{ exp.id }} </td>
                <td> {{ exp.user_name }} </td>
                <td> {{ exp.date }} </td>
                <td> {{ exp.script_set.count }} </td>
                <td> <a href=" {% url 'setupExperimentApp:view_experiment' exp.id %} "> View Experiment {{ exp.id }}  scripts </a> </td>
            </tr>
            {% endfor %}
        </table>
        <p>
            <a href="{% url 'setupExperimentApp:new_experiment'%}"> Add New Experiment </a>
        </p>
    </body> 
</html> 

setupExperimentApp/templates/new_experiment.html
<!DOCTYPE html> 

<html>
    <head> 
        <meta charset="utf-8"> 
        <title> Add a New Experiment </title>
    </head>


    <body>
        <!-- <form action=" url 'setupExperimentApp:edit_experiments' " method='post'> -->
        <form action='.' method='post'>
            {%csrf_token %} 
            {{ form.as_p }}
            <button name = "submit">Add Experiment</button>
        </form>
    
    </body>

setupExperimentApp/templates/new_script.html
<!DOCTYPE html> 

<html>
    <head> 
        <meta charset="utf-8"> 
        <title> Add a New Script </title>
    </head>


    <body>
        <form action='.' method='post'>
            {%csrf_token %} 
            {{ form.as_p }}
            <button name = "submit">Add Script</button>
        </form>
    
    </body>

setupExperimentApp/templates/view_experiment.html
<!DOCTYPE html> 

<html>
    <head> 
        <meta charset="utf-8"> 
        <style>
            table, th, td { border: 1px solid black;}
        </style>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.3/Chart.min.js"></script>

    </head>

    <body>
        <h1> Edit An Experiment's Details </h1>
        <!--  ExperimentForm() used for editing a specific experiment's model fields  -->

        <h3>
            experiment #{{ id }} / name: {{ user_name }} / date: {{ date }} 
        </h3>

        <a href=" {% url 'setupExperimentApp:edit_experiment' id %} "> Edit Experiment User Name </a> 

        <body>
            <h4> Script Index </h4>
            <table>
                <tr>
                    <th> Script Name </th>
                    <th> Script Configurations </th>
                </tr>
                {% for script in script_set %}
                <tr>
                    <td> {{ script.type }} </td> 
                    <td>
                        
                        <canvas id="myChart{{script.id}}"></canvas>
                        
                    </td>
                    <td>

                        {{ script.graphJSON | safe }}

                        <div class="graph_container">
                            <script type="text/javascript" scriptID={{script.id}}>
                                // var chart = document.currentScript.getAttribute('scriptChart');
                                var chart = {{ script.graphJSON | safe }};  
                                var scriptID = document.currentScript.getAttribute('scriptID' ); 
                                console.log('script chart:', chart);
                                console.log('script id:', scriptID);
                                var ctx = document.getElementById("myChart{{script.id}}").getContext('2d');
                                var myChart{{script.id}} = new Chart(ctx, chart)  
                                        
                                /* 
                                    options: {
                                            hover :{
                                            animationDuration:10
                                        },
                                        scales: {
                                            xAxes: [{
                                                label:"Duration",
                                                ticks: {
                                                    beginAtZero:true,
                                                    fontFamily: "'Open Sans Bold', sans-serif",
                                                    fontSize:11
                                                },
                                                scaleLabel:{
                                                    display:false
                                                },
                                                gridLines: {
                                                },
                                                stacked: true
                                            }],
                                            yAxes: [{
                                                gridLines: {
                                                    display:false,
                                                    color: "#fff",
                                                    zeroLineColor: "#fff",
                                                    zeroLineWidth: 0
                                                },
                                                ticks: {
                                                    fontFamily: "'Open Sans Bold', sans-serif",
                                                    fontSize:11
                                                },
                                                stacked: true
                                            }]
                                        },
                                        legend:{
                                            display:false
                                        },
                                    }
                                }); 
                            */
                            
                            </script>
                        </div>
                    </td> 
                </tr>
                {% endfor %}

            </table>
        <a href=" {% url 'setupExperimentApp:new_script' id %} "> Add New Script </a> 
        
        <!-- chartJSON = {{chartJSON}} -->

       <!--<script> 
        var ctx = document.getElementById("myChart");
        var myChart = new Chart(ctx, {
            type: 'horizontalBar',
            data: {
                labels: ["open door", "wait", "close door", "etc"],
                datasets: [{
                    data: [50, 150, 300, 400, 500],
                    backgroundColor: "rgba(63,103,126,0)",
                    hoverBackgroundColor: "rgba(50,90,100,0)"
                },{
                    data: [100, 100, 200, 200, 100],
                    backgroundColor: ['red', 'green', 'blue', 'yellow'],
                }]
            },
            // options: barOptions_stacked,
        });
        // this part to make the tooltip only active on your real dataset
        /* var originalGetElementAtEvent = myChart.getElementAtEvent;
        myChart.getElementAtEvent = function (e) {
            return originalGetElementAtEvent.apply(this, arguments).filter(function (e) {
                return e._datasetIndex === 1;
            });
        }
                //# sourceURL=pen.js */
          
        </script> -->
        <!--
        <script type="text/javascript">
            console.log('In Script Tag to display myChart'); 
            var data = {{ chartJSON | safe }}; 
            var ctx = document.getElementById("myChart").getContext('2d');
            var myChart = new Chart(ctx, data);

        </script>    
        -->
    </body>

    
    </body>